### ISSUE TITLE
真是 -> 真实

### ISSUE THREAD

**Issue by feiyang233** [lonegunmanb/introduction-terraform#1]
您翻译得太棒了，感谢.

这里有一个词语错误
https://lonegunmanb.github.io/introduction-terraform/5.16.refresh.html
它可以用来检测 ~~真是~~ 状态与记录状态之间的漂移并更新状态文件。

**Comment by lonegunmanb** [comment]
> 您翻译得太棒了，感谢.
> 
> 这里有一个词语错误
> https://lonegunmanb.github.io/introduction-terraform/5.16.refresh.html
> 它可以用来检测 ~真是~ 状态与记录状态之间的漂移并更新状态文件。

非常感谢您的指正，希望您有一个愉快的阅读体验！
