### ISSUE TITLE
请问能提供epub或pdf版本吗？

### ISSUE THREAD

**Issue by lihz1990** [lonegunmanb/introduction-terraform#10]
您好，请问能提供epub或者pdf格式文档，方便在离线阅读器上学习、做笔记吗？

**Comment by lonegunmanb** [comment]
@lihz1990 感谢提出这个请求，有意思，感觉可以考虑，我试一下，行的话我把路径放在这里回复你。

**Comment by lihz1990** [comment]
感谢回应，我刚才尝试按照epub格式将仓库中的html手动打包成epub电子书，但出来的样式不太理想。如果有原始的文档，比如markdown，或许会简单一些。

**Comment by lonegunmanb** [comment]
@lihz1990 https://github.com/lonegunmanb/introduction-terraform/releases/tag/2024-12-26
