### ISSUE TITLE
"马驰"是谁？为啥要排除他？

### ISSUE THREAD

**Issue by CoffeeHi** [lonegunmanb/introduction-terraform#5]
纯粹好奇😁

**Comment by cobb-tx** [comment]
哈哈 我也是这么想的

**Comment by cobb-tx** [comment]
对于这本书我再安利一下，目前中国人参加 ACM(acm.org，计算机协会)年费有折扣，折下来160+一年，可以在 [learning.acm.org](https://learning.acm.org/) 上进入 O'REILLY 在线学习中心畅读大量 O'REILLY 的电子书，非常划算，基本读两三本就回本了。这本书也可以通过这种方式在线阅读。
这个已经不行了

**Comment by lonegunmanb** [comment]
> 对于这本书我再安利一下，目前中国人参加 ACM(acm.org，计算机协会)年费有折扣，折下来160+一年，可以在 [learning.acm.org](https://learning.acm.org/) 上进入 O'REILLY 在线学习中心畅读大量 O'REILLY 的电子书，非常划算，基本读两三本就回本了。这本书也可以通过这种方式在线阅读。 这个已经不行了

因为公司图书馆已经包含了 O'Reilly 所以我很久没续费 ACM 了，刚看了下中国 [CCF](https://www.ccf.org.cn/Membership/Individual_member/Join_Sister_Societies/Join_ACM/) ，似乎要看电子图书馆涨价了。。。不过这本书也已经有中译版了。

感谢提醒。@cobb-tx

**Comment by cobb-tx** [comment]
@lonegunmanb  羡慕  我不是先看这本书 我想看其他的书籍的   O'Reilly出版的   CCF能看嘛  ACM好像不行了 因为 O'Reilly自己出了会员而且价格还不低

**Comment by cobb-tx** [comment]
@lonegunmanb  羡慕  我不是先看这本书 我想看其他的书籍的   O'Reilly出版的   CCF能看嘛  ACM好像不行了 因为 O'Reilly自己出了会员而且价格还不低

**Comment by lonegunmanb** [comment]
> @lonegunmanb  羡慕  我不是先看这本书 我想看其他的书籍的   O'Reilly出版的   CCF能看嘛  ACM好像不行了 因为 O'Reilly自己出了会员而且价格还不低   

估计不行。听下来不少外企都购买了 O'Reilly 的数字图书馆的。

**Comment by feel-easy** [comment]
马驰 ？？？ 求作者讲一下 👀

**Comment by lonegunmanb** [comment]
> 马驰 ？？？ 求作者讲一下 👀

我们多做一些有意义的事吧。去创造去贡献一些东西。

**Comment by 631086083** [comment]
本来想开个issue问下的，发现已经有了，求作者讲一下故事，非常想吃瓜
