### ISSUE TITLE
Test里代码貌似有点小问题

### ISSUE THREAD

**Issue by GameHab** [lonegunmanb/introduction-terraform#7]
https://lonegunmanb.github.io/introduction-terraform/6.test.html 
里面的`1.7.1.2.1. 示例` ，`1.7.1.5. provider 块`中的代码：
```terraform
re
e "aws_s3_bucket" "bucket" {
  bucket = "${var.bucket_prefix}-bucket"
}
```
是
```terraform
resource "aws_s3_bucket" "bucket" {
  bucket = "${var.bucket_prefix}-bucket"
}
```
吗？
Ps:看完对入门terraform很有帮助，感谢！

**Comment by lonegunmanb** [comment]
的确如此，非常感谢您的指正，最近在大幅更新本书内容以应对版本更新。我会尽快更正你指出的错误。再次感谢！

**Comment by lonegunmanb** [comment]
I'm closing this issue since it has been fixed, thanks @GameHab
