### ISSUE TITLE
请问有 "1.5.5.1.2. 探索遵循这些原则的一个示例场景" 这个场景的terraform代码样例吗?

### ISSUE THREAD

**Issue by sunxiang0918** [lonegunmanb/introduction-terraform#8]
请问有 "1.5.5.1.2. 探索遵循这些原则的一个示例场景" 这个场景的terraform代码样例吗?
或者是一个完整的稍微复杂一点的 terraform代码的示例?
谢谢~

**Comment by lonegunmanb** [comment]
@sunxiang0918 感谢您的提问。[设计新模块的模式](https://lonegunmanb.github.io/introduction-terraform/4.5.%E8%AE%BE%E8%AE%A1%E6%96%B0%E6%A8%A1%E5%9D%97%E7%9A%84%E6%A8%A1%E5%BC%8F.html) 一节本身描述了如何对一个网络应用进行分层开始进行模块化设计的思考过程，并没有具体的实现代码，但您可以参考这个分层的思考过程来对您的应用进行拆解和建模。实际上模块化的 Terraform 代码设计的最佳实践基本上由 [Terragrunt](https://terragrunt.gruntwork.io/docs/) 总结的比较完善了，推荐参考他们示例中的架构。
