### ISSUE TITLE
第四章缺失正文

### ISSUE THREAD

**Issue by i-abc** [lonegunmanb/introduction-terraform#9]
你好，[第四章](https://lonegunmanb.github.io/introduction-terraform/4.Terraform%E6%96%87%E4%BB%B6%E4%B8%8E%E7%9B%AE%E5%BD%95/)整章缺失正文，其他章节正常：
![image](https://github.com/user-attachments/assets/b9746e3f-8ecd-4ee5-b29e-1ea7f8c5761c)

**Comment by ellaann** [comment]
遇到了同样的问题lol，望作者大大得空修复一下，感恩。

**Comment by Auditore8** [comment]
是的 完全看不到

**Comment by lonegunmanb** [comment]
@i-abc Thanks for opening this issue and thanks for reply @Auditore8 @ellaann , I'm closing this issue since the missing chapters have been amended.
